spring:
  application:
    name: blog-web

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?useUnicode=true&characterEncoding=utf-8&userSSL=false&serverTimezone=GMT%2B8 # %2B
    #    url: jdbc:mysql://localhost:3306/blog
    username: root
    password: admin

  devtools:
    restart:
      enabled: true

mybatis-plus:
  #The classpath*:conf/appContext.xml simply means that allx appContext.xml files under conf folders in all your jars on the classpath will be picked up and joined into one big application context.
  #In contrast, classpath:conf/appContext.xml will load only one such file... the first one found on your classpath.
  mapper-locations: classpath*:/mapper/*.xml

server:
  port: 8080
  servlet:
    session:
      timeout: 60

enable:
  swagger2: true

